# Generated by Django 4.2.2 on 2023-06-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        (
            "projects",
            "0002_tag_project_total_votes_project_votes_ratio_review_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_text",
            new_name="body",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                default="project_images/default.jpg",
                null=True,
                upload_to="project_images",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[
                    ("up", "Положительная оценка"),
                    ("down", "Отрицательная оценка"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "project")},
        ),
    ]
